"""
main.py — CLI entry point for the /validate quality gate.

Usage:
  python .agents/skills/validate/main.py <FEATURE_NAME>

Orchestrates the multi-crew pipeline:
  1. SpecCrew & CodeCrew (Parallel)
  2. DeliveryCrew (Sequential)
  3. CouncilCrew (Sequential)

Design: DESIGN_VALIDATE_WORKFLOW.md v2.0
"""

import sys
from pathlib import Path
import typer
from rich.console import Console
from rich.table import Table
from rich.panel import Panel

# main.py lives in scripts/, so:
#   __file__ → .agents/skills/validate/scripts/main.py
#   .parent  → .agents/skills/validate/scripts/
#   .parent.parent → .agents/skills/validate/  (the validate package root)
#   .parent.parent.parent → .agents/skills/      (on sys.path so `from scripts...` works)
sys.path.insert(0, str(Path(__file__).parent.parent.parent))  # skills/
sys.path.insert(0, str(Path(__file__).parent.parent))         # validate/

# Import from the scripts sub-package (where all code actually lives)
from scripts import ValidateSkill
from scripts.schemas import ValidationReport

app = typer.Typer(help="AgentSpec /validate quality gate.")
console = Console()

SDD_FEATURES_DIR = Path(".agents/sdd/features")


def _generate_artifact(feature_name: str, type: str, content: str):
    """Save RUNBOOK or ROADMAP artifact to disk."""
    filename = f"{type}_{feature_name}.md"
    target_path = SDD_FEATURES_DIR / filename

    # Simple template for the artifact
    header = f"# {type}: {feature_name}\n\nGenerated by Antigravity /validate quality gate.\n\n"
    target_path.write_text(header + content, encoding="utf-8")
    console.print(f"[bold green]✅ Artifact generated:[/bold green] {target_path}")


@app.command()
def validate(
    feature_name: str = typer.Argument(..., help="Feature name to validate (e.g. VALIDATE_WORKFLOW)")
):
    """Execute the full multi-agent validation pipeline."""
    console.print(Panel(f"[bold blue]🚀 Starting Validation for: {feature_name}[/bold blue]"))

    try:
        skill = ValidateSkill(feature_name)
        report: ValidationReport = skill.run()
    except FileNotFoundError as e:
        console.print(f"[bold red]❌ Error:[/bold red] {e}")
        raise typer.Exit(code=1)
    except Exception as e:
        console.print(f"[bold red]❌ Pipeline Failed:[/bold red] {e}")
        raise typer.Exit(code=1)

    # ── Summary Display ────────────────────────────────────────────────────
    console.print("\n[bold]Validation Summary[/bold]")
    table = Table(show_header=True, header_style="bold magenta")
    table.add_column("Dimension", style="dim")
    table.add_column("Score", justify="right")

    for dim, score in report.dimensions.items():
        color = "green" if score >= 85 else "yellow" if score >= 70 else "red"
        table.add_row(dim, f"[{color}]{score:.1f}%[/{color}]")

    table.add_section()
    final_color = "green" if report.score >= 90 else "yellow" if report.score >= 70 else "red"
    table.add_row("[bold]TOTAL SCORE[/bold]", f"[{final_color}][bold]{report.score:.1f}%[/bold][/{final_color}]")
    console.print(table)

    # ── Verdict ────────────────────────────────────────────────────────────
    console.print(f"\n[bold]Status:[/bold] {report.status}")
    if report.summary:
        console.print(Panel(report.summary, title="Executive Summary"))

    # ── Critical Issues ────────────────────────────────────────────────────
    if report.critical_issues:
        console.print("\n[bold red]🚫 CRITICAL ISSUES (Blocking Artifacts):[/bold red]")
        for issue in report.critical_issues:
            console.print(f"- [red]{issue.title}:[/red] {issue.description}")

    # ── Artifact Generation ────────────────────────────────────────────────
    if report.runbook_eligible:
        _generate_artifact(feature_name, "RUNBOOK", "## Production Operations\nReady for deployment.")
    elif report.roadmap_eligible:
        _generate_artifact(feature_name, "ROADMAP", "## Implementation Roadmap\nRequires targeted improvements.")
    else:
        console.print("\n[bold yellow]⚠️ Feature not eligible for Runbook or Roadmap artifacts.[/bold yellow]")

    if report.status == "FAILED" or report.score < 70:
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
